# Generated by Django 3.2.15 on 2022-09-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('house_name', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('road_name', models.CharField(max_length=250)),
                ('pincode', models.IntegerField()),
                ('mobile', models.IntegerField()),
            ],
        ),
    ]
